// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgoxOjy_RsFp3Aq-noaCp4HP3RJcZMcvM',
    appId: '1:850386387843:web:d06577b5fca46cc16dacb6',
    messagingSenderId: '850386387843',
    projectId: 'g-t-c-d064c',
    authDomain: 'g-t-c-d064c.firebaseapp.com',
    storageBucket: 'g-t-c-d064c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAisigdDqS_kd7Pu4YUPzA4nHUsJCR2gIU',
    appId: '1:850386387843:android:9d921ef4f1e060266dacb6',
    messagingSenderId: '850386387843',
    projectId: 'g-t-c-d064c',
    storageBucket: 'g-t-c-d064c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Z5Rlnu9Gy5NdpPqIGE1LzprWLMf4jv8',
    appId: '1:850386387843:ios:2013afdc12c688406dacb6',
    messagingSenderId: '850386387843',
    projectId: 'g-t-c-d064c',
    storageBucket: 'g-t-c-d064c.appspot.com',
    iosBundleId: 'com.gtc.database',
  );
}
